version: "3.9"
services:

  frontend:
    build: Frontend/.
    restart: on-failure
    ports:
      - "4567:4567"
    depends_on:
      - item
      - user
      - auction
      - payment
      - cart
    links:
      - mongo_frontend
    environment:
      WAIT_HOSTS: mongo_frontend:27017
    volumes:
      - ./Frontend:/code

  auction:
    build: Auction/.
    restart: on-failure
    depends_on:
      - user
      - messenger
      - mongo
    environment:
      WAIT_HOSTS: rabbit-mq:5672
      TZ: "America/Chicago"
    volumes:
      - ./Auction:/code

  messenger:
    build: Messenger/.
    restart: on-failure
    ports:
      - "465:465"
    links:
      - rabbit-mq
    environment:
      WAIT_HOSTS: rabbit-mq:5672
    volumes:
      - ./Messenger:/code

  user:
    build: User/.
    restart: on-failure
    volumes:
      - ./User:/code
    environment:
      WAIT_HOSTS: mysql-user:3306
    depends_on:
      - mysql-user

  cart:
    build: Shopping_Cart/.
    restart: on-failure
    volumes:
      - ./Shopping_Cart:/code
    environment:
      WAIT_HOSTS: mysql-cart:3306
    depends_on:
      - mysql-cart

  item:
    build: Item/.
    restart: on-failure
    volumes:
      - ./Item:/code
    environment:
      WAIT_HOSTS: postgresql-db:5432
      TZ: "America/Chicago"
    depends_on:
      - postgresql-db

  payment:
    build: Payment/.
    restart: on-failure
    depends_on:
      - user
    links:
      - mongo_payment
    volumes:
      - ./Payment:/code
  
  mongo_frontend:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: LoginService

  mongo_auction:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: auctionSite

  mongo_payment:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Bank

  postgresql-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: test

  rabbit-mq:
    image: rabbitmq:3-alpine
    restart: always

  mysql-user:
    image: ubuntu/mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secretpass
      MYSQL_DATABASE: userData

  mysql-cart:
    image: ubuntu/mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secretpass
      MYSQL_DATABASE: Cart

